temperature/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt

from graphene_django.views import GraphQLView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tempquiz.urls")),
    path("graphql", csrf_exempt(GraphQLView.as_view(graphiql=True))),
]

tempquiz/urls.py
from django.urls import path

from .views import HomePageView, AboutPageView

urlpatterns = [
    path("about/", AboutPageView.as_view(), name="about"),
    path("", HomePageView.as_view(), name="home"),
]

tempquiz/models.py
from django.db import models
import time


class Temperature(models.Model):
    timestamp = models.DateTimeField(auto_now=True)
    value = models.FloatField(float)

    def __str__(self) -> str:
        return f"at {self.timestamp} the temperature is {self.value}"

tempquiz/views.py
from django.views.generic import TemplateView, ListView
from .models import Temperature


class HomePageView(ListView):
    model = Temperature
    template_name = "home.html"


class AboutPageView(TemplateView):
    template_name = "about.html"

templates/about.html
{% extends "base.html" %}

{% block content %}
<h1>About page</h1>
{% endblock content %}

templates/base.html
<header>
    <a href="{% url 'home' %}">Home</a> |
    <a href="{% url 'about' %}">About</a>
</header>

{% block content %} {% endblock content %}

templates/home.html
{% extends "base.html" %}

{% block content %}
<h1>Temperature Readings</h1>
<ul>
    {% for value in temperature_list %}
    <li>{{ value.timestamp }} {{ value.value}}</li>
    {% endfor %}
</ul>
{% endblock content %}